#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# Trigger CD when CI executed succesfully
resources:
  pipelines:
    - pipeline: eshoponweb-ci
      source: eshoponweb-ci # given pipeline name
      trigger: true


variables:
  resource-group: 'rg-eshoponweb-secure'
  location: 'southcentralus'
  templateFile: '.azure/bicep/webapp.bicep'
  subscriptionid: 'da41d269-7fa0-4848-a1d8-e6ae989a020e'
  azureserviceconnection: 'Visual Studio Enterprise Subscription'
  webappname: 'eshoponweb-lab-secure-mmf-test'
  # webappname: 'webapp-windows-eshop'
  

stages:
- stage: Deploy
  displayName: Deploy to WebApp
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    #download artifacts
    - download: eshoponweb-ci
  
    # Deploy App Service Plan + App Service using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service Plan Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: '-webAppName $(webappname) -location $(location)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'asp-json'
    
    #Publish Website to Azure WebApp
    - task: AzureRmWebAppDeployment@4
      displayName: Publish Website to WebApp
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'azure subs'
        appType: 'webApp'
        WebAppName: '$(webappname)'
        packageForLinux: '$(Pipeline.Workspace)/**/Web.zip'
      

    
